/* Generated by ZER compiler — do not edit */
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

/* ZER optional types */
typedef struct { uint8_t value; uint8_t has_value; } _zer_opt_u8;
typedef struct { uint16_t value; uint8_t has_value; } _zer_opt_u16;
typedef struct { uint32_t value; uint8_t has_value; } _zer_opt_u32;
typedef struct { uint64_t value; uint8_t has_value; } _zer_opt_u64;
typedef struct { int8_t value; uint8_t has_value; } _zer_opt_i8;
typedef struct { int16_t value; uint8_t has_value; } _zer_opt_i16;
typedef struct { int32_t value; uint8_t has_value; } _zer_opt_i32;
typedef struct { int64_t value; uint8_t has_value; } _zer_opt_i64;
typedef struct { size_t value; uint8_t has_value; } _zer_opt_usize;
typedef struct { float value; uint8_t has_value; } _zer_opt_f32;
typedef struct { double value; uint8_t has_value; } _zer_opt_f64;
typedef struct { uint8_t has_value; } _zer_opt_void;

/* ZER slice types */
typedef struct { uint8_t* ptr; size_t len; } _zer_slice_u8;
typedef struct { uint32_t* ptr; size_t len; } _zer_slice_u32;

/* ZER Pool runtime */
#define _ZER_POOL_DECL(NAME, ELEM_TYPE, CAPACITY) \
    struct { \
        ELEM_TYPE slots[CAPACITY]; \
        uint16_t gen[CAPACITY]; \
        uint8_t used[CAPACITY]; \
    } NAME = {0}

static inline uint32_t _zer_pool_alloc(void *pool_ptr, size_t slot_size, uint16_t *gen, uint8_t *used, uint32_t capacity, uint8_t *ok) {
    for (uint32_t i = 0; i < capacity; i++) {
        if (!used[i]) {
            used[i] = 1;
            *ok = 1;
            return (uint32_t)((gen[i] << 16) | i);
        }
    }
    *ok = 0;
    return 0;
}

static void _zer_trap(const char *msg, const char *file, int line) {
#ifdef __arm__
    /* ARM embedded: infinite loop with breakpoint */
    (void)msg; (void)file; (void)line;
    __asm__ volatile("bkpt #0");
    for(;;) {}
#else
    /* Hosted: print diagnostic and abort */
    fprintf(stderr, "ZER TRAP: %s at %s:%d\n", msg, file, line);
    abort();
#endif
}

static inline void _zer_bounds_check(size_t idx, size_t len, const char *file, int line) {
    if (idx >= len) _zer_trap("array index out of bounds", file, line);
}

static inline void *_zer_pool_get(void *slots, uint16_t *gen, uint8_t *used, size_t slot_size, uint32_t handle, uint32_t capacity) {
    uint32_t idx = handle & 0xFFFF;
    uint16_t h_gen = (uint16_t)(handle >> 16);
    if (idx >= capacity || !used[idx] || gen[idx] != h_gen) {
        _zer_trap("use-after-free: handle generation mismatch", __FILE__, __LINE__);
    }
    return (char*)slots + idx * slot_size;
}

static inline void _zer_pool_free(uint16_t *gen, uint8_t *used, uint32_t handle, uint32_t capacity) {
    uint32_t idx = handle & 0xFFFF;
    if (idx < capacity) {
        used[idx] = 0;
        gen[idx]++;
    }
}

/* ZER Ring runtime */
#define _ZER_RING_DECL(NAME, ELEM_TYPE, CAPACITY) \
    struct { \
        ELEM_TYPE data[CAPACITY]; \
        uint32_t head; \
        uint32_t tail; \
        uint32_t count; \
        uint32_t capacity; \
    } NAME = { .capacity = CAPACITY }

static inline void _zer_ring_push(void *ring_data, uint32_t *head, uint32_t *count, uint32_t capacity, const void *val, size_t elem_size) {
    memcpy((char*)ring_data + (*head) * elem_size, val, elem_size);
    *head = (*head + 1) % capacity;
    if (*count < capacity) (*count)++;
}


uint32_t add(uint32_t a, uint32_t b) {
    return (a + b);
}

uint32_t multiply(uint32_t a, uint32_t b) {
    return (a * b);
}


/* --- imported module --- */

uint32_t main(void) {
    uint32_t sum = add(3, 4);
    uint32_t product = multiply(5, 6);
    return (sum + product);
}

