/* src/safety/asm_register_lookup.c — register-table lookup function.
 *
 * D-Alpha-7.5 Session F2. Implements zer_asm_register_valid (declared in
 * asm_register_tables.h) via linear scan over the vendored per-arch
 * tables generated by scripts/gen_register_tables.sh.
 *
 * F2: x86_64 only. F5/F6 add aarch64/riscv64 dispatch.
 *
 * VST-friendly C style: flat cascade, no compound conditions. Future
 * Phase 1 extraction (Session H) wraps this as the @asm_register_valid
 * predicate for verification against the linked vendored data.
 */
#include <string.h>
#include "asm_register_tables.h"

/* Internal: scan a single table. Linear scan suffices for current N. */
static int scan_table(const ZerRegisterEntry *table, const char *name, size_t name_len) {
    if (table == 0) {
        return 0;
    }
    for (size_t i = 0; table[i].name != 0; i++) {
        if (table[i].name_len != name_len) {
            continue;
        }
        if (memcmp(table[i].name, name, name_len) == 0) {
            return 1;
        }
    }
    return 0;
}

int zer_asm_register_valid(ZerArchId arch, const char *name, size_t name_len) {
    return zer_asm_register_valid_with_features(arch, ZER_FEAT_NONE, name, name_len);
}

int zer_asm_register_valid_with_features(
    ZerArchId arch,
    uint32_t features,
    const char *name,
    size_t name_len)
{
    if (name == 0) {
        return 0;
    }
    if (name_len == 0) {
        return 0;
    }

    if (arch == ZER_ARCH_X86_64) {
        /* C4-minimum: feature-aware dispatch. AVX-512F unlocks the
         * extended table (160 entries vs base 104). Other features
         * (SHA-NI, AES-NI etc.) added the same way as F4 progresses. */
        if (features & ZER_FEAT_AVX512F) {
            if (scan_table(zer_x86_64_avx512f_registers, name, name_len)) {
                return 1;
            }
        }
        /* Always check base table — AVX-512 table is a superset, but
         * checking base is defense in depth and keeps base regs
         * verifiable even if features are incorrectly set. */
        return scan_table(zer_x86_64_registers, name, name_len);
    }

    /* aarch64 dispatch — universality proof. Same lookup framework
     * extends across ISAs. Future SVE/SVE2/SME features added here as
     * separate per-feature tables (when GCC strictly gates them, like
     * AVX-512). For now: aarch64 GCC backend accepts SVE register
     * names without a strict +sve flag, so base table includes them. */
    if (arch == ZER_ARCH_AARCH64) {
        return scan_table(zer_aarch64_registers, name, name_len);
    }

    /* F6 will add riscv64 dispatch — same pattern. */

    return 0;
}
