/* AUTO-GENERATED by scripts/gen_register_tables.sh — DO NOT EDIT BY HAND.
 * Regenerate via: make gen-asm-tables
 *
 * Source: GCC probe of register clobber acceptance for arch=x86_64.
 * Compiler: gcc (Docker image: gcc:13)
 * Generated: 2026-04-26
 *
 * Vendored for reproducible builds + LSP-responsive runtime lookup.
 * D-Alpha-7.5 Session F2 (build-time-gen pipeline).
 */
#include "asm_register_tables.h"

const ZerRegisterEntry zer_x86_64_registers[] = {
    {"rax", 3},
    {"rbx", 3},
    {"rcx", 3},
    {"rdx", 3},
    {"rsi", 3},
    {"rdi", 3},
    {"rsp", 3},
    {"r8", 2},
    {"r9", 2},
    {"r10", 3},
    {"r11", 3},
    {"r12", 3},
    {"r13", 3},
    {"r14", 3},
    {"r15", 3},
    {"eax", 3},
    {"ebx", 3},
    {"ecx", 3},
    {"edx", 3},
    {"esi", 3},
    {"edi", 3},
    {"esp", 3},
    {"ax", 2},
    {"bx", 2},
    {"cx", 2},
    {"dx", 2},
    {"si", 2},
    {"di", 2},
    {"sp", 2},
    {"al", 2},
    {"bl", 2},
    {"cl", 2},
    {"dl", 2},
    {"sil", 3},
    {"dil", 3},
    {"spl", 3},
    {"ah", 2},
    {"bh", 2},
    {"ch", 2},
    {"dh", 2},
    {0, 0}  /* sentinel */
};

const size_t zer_x86_64_register_count = 40;
