/* src/safety/asm_register_tables.h — vendored per-arch register tables.
 *
 * D-Alpha-7.5 Session F2: build-time generation pipeline.
 *
 * Tables are generated by scripts/gen_register_tables.sh which probes
 * GCC for register validity per arch. Output committed to git for
 * reproducible builds; runtime is fast hash/scan lookup.
 *
 * F2: x86_64 only. F5/F6 add aarch64/riscv64 tables.
 *
 * Architecture decision: build-time-gen + vendored output. Pattern
 * matches LLVM TableGen, ICU Unicode, Linux autoconf, libc++ locale
 * data. See docs/asm_plan.md "SESSIONS C + F ARCHITECTURE" notice.
 */
#ifndef ZER_ASM_REGISTER_TABLES_H
#define ZER_ASM_REGISTER_TABLES_H

#include <stddef.h>
#include "asm_categories.h"  /* for ZerArchId */

/* Register table entry. Reserved fields for future register-class
 * tagging (GP, SIMD, FPU, special) when O3 (per-arch register
 * validation) needs them. */
typedef struct {
    const char *name;
    size_t name_len;
} ZerRegisterEntry;

/* Per-arch tables. extern declarations; definitions in arch-specific
 * AUTO-GENERATED .c files committed by scripts/gen_register_tables.sh.
 *
 * F2: only x86_64 table is populated. ARM64/RISC-V symbols below are
 * declared but their .c files don't exist yet — the lookup function
 * handles the missing case gracefully. */
extern const ZerRegisterEntry zer_x86_64_registers[];
extern const size_t zer_x86_64_register_count;

/* Look up whether a register name is valid for the given arch.
 * Returns 1 (valid), 0 (invalid or arch unsupported).
 *
 * Linear scan today (small N). Hash table can replace if needed
 * (Phase 1 extraction in Session H wraps this for VST verification).
 *
 * Matches the pattern of other src/safety/ pure predicates: same
 * inputs always produce the same output, suitable for VST proof
 * against the linked vendored data. */
int zer_asm_register_valid(ZerArchId arch, const char *name, size_t name_len);

#endif /* ZER_ASM_REGISTER_TABLES_H */
