/* src/safety/asm_register_tables.h — vendored per-arch register tables.
 *
 * D-Alpha-7.5 Session F2: build-time generation pipeline.
 *
 * Tables are generated by scripts/gen_register_tables.sh which probes
 * GCC for register validity per arch. Output committed to git for
 * reproducible builds; runtime is fast hash/scan lookup.
 *
 * F2: x86_64 only. F5/F6 add aarch64/riscv64 tables.
 *
 * Architecture decision: build-time-gen + vendored output. Pattern
 * matches LLVM TableGen, ICU Unicode, Linux autoconf, libc++ locale
 * data. See docs/asm_plan.md "SESSIONS C + F ARCHITECTURE" notice.
 */
#ifndef ZER_ASM_REGISTER_TABLES_H
#define ZER_ASM_REGISTER_TABLES_H

#include <stddef.h>
#include <stdint.h>
#include "asm_categories.h"  /* for ZerArchId */

/* Register table entry. Reserved fields for future register-class
 * tagging (GP, SIMD, FPU, special) when O3 (per-arch register
 * validation) needs them. */
typedef struct {
    const char *name;
    size_t name_len;
} ZerRegisterEntry;

/* Per-arch tables. extern declarations; definitions in arch-specific
 * AUTO-GENERATED .c files committed by scripts/gen_register_tables.sh.
 *
 * F2: only x86_64 table is populated. ARM64/RISC-V symbols below are
 * declared but their .c files don't exist yet — the lookup function
 * handles the missing case gracefully. */
extern const ZerRegisterEntry zer_x86_64_registers[];
extern const size_t zer_x86_64_register_count;

/* C4-minimum proof: AVX-512 enabled table (probed with
 * -mavx512f -mavx512vl -mavx512bw). 160 valid registers (vs base
 * x86_64's 104). Selected when caller passes ZER_FEAT_AVX512F. */
extern const ZerRegisterEntry zer_x86_64_avx512f_registers[];
extern const size_t zer_x86_64_avx512f_register_count;

/* aarch64 base table — proves universality of the framework across
 * different ISAs. Generated by probing aarch64-linux-gnu-gcc with
 * the standard candidate list. Includes GP (x0-x30, sp), 32-bit (w0-w30),
 * SIMD/FP (v/q/d/s/h/b 0-31), and SVE (z/p 0-31, ffr). 57 entries.
 * Same framework, different arch — proves per-arch dispatch in lookup. */
extern const ZerRegisterEntry zer_aarch64_registers[];
extern const size_t zer_aarch64_register_count;

/* riscv64 base table — F6-minimum (2026-04-29). Generated by probing
 * riscv64-linux-gnu-gcc with the standard candidate list. Includes
 * numbered GP (x0-x31, x8 reserved as fp), ABI names (zero/ra/sp/gp/tp/
 * t0-t6/s1-s11/a0-a7), and FP (f0-f31, ft/fs/fa). 126 entries.
 * Vector extension (V) deferred to F6-extensions. */
extern const ZerRegisterEntry zer_riscv64_registers[];
extern const size_t zer_riscv64_register_count;

/* CPU feature bitmap. Per-feature register tables exist for each
 * meaningful flag. Today: only AVX512F shipped. Future expansions:
 * ARM SVE (when F5 lands), RISC-V V (when F6 lands), x86 SHA/AES-NI,
 * etc.
 *
 * The framework is universal: per-arch base table + per-feature
 * extension tables. A function compiled with feature X must use
 * the corresponding table for register name validation, AND the
 * emitter must propagate the equivalent target attribute / `-m` flag
 * to GCC. End-to-end consistency between checker validation and
 * GCC's actual behavior. */
typedef enum {
    ZER_FEAT_NONE     = 0,
    ZER_FEAT_AVX512F  = 1u << 0,  /* x86: AVX-512 Foundation */
    /* Future: ZER_FEAT_AVX512VL, _AVX512BW, _SVE, _SVE2, _RVV, etc. */
} ZerCpuFeature;

/* Look up whether a register name is valid for the given arch.
 * Returns 1 (valid), 0 (invalid or arch unsupported).
 *
 * Today's signature uses default features (ZER_FEAT_NONE). The
 * feature-aware variant zer_asm_register_valid_with_features lets
 * the caller specify enabled CPU features (e.g., AVX-512). */
int zer_asm_register_valid(ZerArchId arch, const char *name, size_t name_len);

/* Feature-aware lookup. C4-minimum proof entry point.
 *
 * features: bitmap of ZerCpuFeature values. Empty = default arch
 * registers only. Set ZER_FEAT_AVX512F to expand x86_64 from 104 to
 * 160 valid registers (xmm/ymm/zmm 16-31, k0-7, etc.).
 *
 * Returns 1 (valid for the feature set), 0 (invalid). */
int zer_asm_register_valid_with_features(
    ZerArchId arch,
    uint32_t features,
    const char *name,
    size_t name_len);

#endif /* ZER_ASM_REGISTER_TABLES_H */
