/* AUTO-GENERATED by scripts/gen_register_tables.sh — DO NOT EDIT BY HAND.
 * Regenerate via: make gen-asm-tables
 *
 * Source: GCC probe of register clobber acceptance for arch=aarch64.
 * Compiler: aarch64-linux-gnu-gcc
 * Generated: 2026-04-26T16:29:29Z
 *
 * Vendored for reproducible builds + LSP-responsive runtime lookup.
 * D-Alpha-7.5 Session F2 (build-time-gen pipeline).
 */
#include "asm_register_tables.h"

const ZerRegisterEntry zer_aarch64_registers[] = {
    {"x0", 2},
    {"x1", 2},
    {"x2", 2},
    {"x3", 2},
    {"x4", 2},
    {"x5", 2},
    {"x6", 2},
    {"x7", 2},
    {"x8", 2},
    {"x9", 2},
    {"x10", 3},
    {"x11", 3},
    {"x12", 3},
    {"x13", 3},
    {"x14", 3},
    {"x15", 3},
    {"x16", 3},
    {"x17", 3},
    {"x18", 3},
    {"x19", 3},
    {"x20", 3},
    {"x21", 3},
    {"x22", 3},
    {"x23", 3},
    {"x24", 3},
    {"x25", 3},
    {"x26", 3},
    {"x27", 3},
    {"x28", 3},
    {"x29", 3},
    {"x30", 3},
    {"sp", 2},
    {"w0", 2},
    {"w1", 2},
    {"w15", 3},
    {"w30", 3},
    {"v0", 2},
    {"v15", 3},
    {"v31", 3},
    {"q0", 2},
    {"q31", 3},
    {"d0", 2},
    {"d31", 3},
    {"s0", 2},
    {"s31", 3},
    {"h0", 2},
    {"h31", 3},
    {"b0", 2},
    {"b31", 3},
    {"z0", 2},
    {"z1", 2},
    {"z16", 3},
    {"z31", 3},
    {"p0", 2},
    {"p7", 2},
    {"p15", 3},
    {"ffr", 3},
    {0, 0}  /* sentinel */
};

const size_t zer_aarch64_register_count = 57;
