/* src/safety/asm_categories.c — universal precondition category dispatch.
 *
 * F1a stub implementation. Returns 0 (no category) for every instruction.
 * Future F4-F6 ship per-arch data tables generated by build-time scripts;
 * the lookup will become a hash table over the vendored data.
 *
 * VST-friendly C style: flat cascade, no compound conditions.
 *
 * Oracle: docs/asm_preconditions_research.md (8 categories formally
 * defined). VST proof in proofs/vst/verif_asm_categories.v will be
 * trivial today (always returns 0) and gain content as tables land.
 */
#include "asm_categories.h"

uint32_t zer_asm_category(ZerArchId arch, const char *insn, size_t insn_len) {
    /* F1a: no per-arch tables exist yet. Always return 0 (no category).
     * Wired so checker.c NODE_ASM can call this without conditional
     * compilation; activates when F4-F6 ship vendored tables. */
    if (arch == ZER_ARCH_UNKNOWN) {
        return 0;
    }
    if (insn == 0) {
        return 0;
    }
    if (insn_len == 0) {
        return 0;
    }
    /* Real implementation (post-F4): hash lookup against the vendored
     * arch-specific table. Each table maps mnemonic -> category bitmap.
     * The table is generated at zerc build time and committed to git. */
    return 0;
}

const char *zer_asm_category_name(uint32_t cat_bitmap) {
    if (cat_bitmap == 0) {
        return "none";
    }
    /* Single-category quick names. For combined bitmaps, return the
     * highest-priority single name; full bitmap rendering is left to
     * the diagnostics caller. */
    if (cat_bitmap & 1u) {
        return "C1 (value-range)";
    }
    if (cat_bitmap & 2u) {
        return "C2 (alignment)";
    }
    if (cat_bitmap & 4u) {
        return "C3 (state-machine)";
    }
    if (cat_bitmap & 8u) {
        return "C4 (cpu-feature)";
    }
    if (cat_bitmap & 16u) {
        return "C5 (privilege)";
    }
    if (cat_bitmap & 32u) {
        return "C6 (memory-addressability)";
    }
    if (cat_bitmap & 64u) {
        return "C7 (provenance)";
    }
    if (cat_bitmap & 128u) {
        return "C8 (memory-ordering)";
    }
    return "unknown";
}
