/* AUTO-GENERATED by scripts/gen_instruction_table.sh — DO NOT EDIT BY HAND.
 * Regenerate via: make gen-asm-tables (or scripts/gen_instruction_table.sh x86_64)
 *
 * Source: arch_data/x86_64.zerdata (per-instruction safety classification)
 * Generated: 2026-04-29T07:43:08Z
 *
 * Vendored for reproducible builds + LSP-responsive runtime lookup.
 * D-Alpha-7.5 Session F4 (instruction-level safety classification).
 *
 * Schema: arch_data/SCHEMA.md
 * Lookup: zer_asm_category(arch, mnemonic, len)
 */
#include "asm_categories.h"
#include "asm_instruction_table.h"

const ZerInstructionEntry zer_x86_64_instructions[] = {
    {"bsr", 3, 1u, 0u, "Intel SDM Vol 2A BSR", "silent UB: destination undefined when source is zero"},
    {"bsf", 3, 1u, 0u, "Intel SDM Vol 2A BSF", "silent UB: destination undefined when source is zero"},
    {"div", 3, 1u, 0u, "Intel SDM Vol 2A DIV", "#DE divide-by-zero exception"},
    {"idiv", 4, 1u, 0u, "Intel SDM Vol 2A IDIV", "#DE on divide-by-zero OR INT_MIN/-1 overflow"},
    {"movaps", 6, 2u, 0u, "Intel SDM Vol 2B MOVAPS", "#GP fault on misaligned memory operand"},
    {"movdqa", 6, 2u, 0u, "Intel SDM Vol 2B MOVDQA", "#GP fault on misaligned memory operand"},
    {"monitor", 7, 20u, 0u, "Intel SDM Vol 2B MONITOR", "#GP fault if executed at CPL > 0; subsequent MWAIT must pair within state machine"},
    {"mwait", 5, 20u, 0u, "Intel SDM Vol 2B MWAIT", "#GP fault if executed at CPL > 0; #UD if MONITOR not preceding"},
    {"vpxorq", 6, 8u, 1u, "Intel SDM Vol 2C VPXORQ", "#UD fault if AVX-512F not enabled at runtime"},
    {"wrmsr", 5, 16u, 0u, "Intel SDM Vol 2B WRMSR", "#GP fault if executed at CPL > 0"},
    {"rdmsr", 5, 16u, 0u, "Intel SDM Vol 2B RDMSR", "#GP fault if executed at CPL > 0"},
    {"invlpg", 6, 16u, 0u, "Intel SDM Vol 2A INVLPG", "#GP fault if executed at CPL > 0"},
    {"hlt", 3, 16u, 0u, "Intel SDM Vol 2A HLT", "#GP fault if executed at CPL > 0"},
    {0, 0, 0u, 0u, 0, 0}  /* sentinel */
};

const size_t zer_x86_64_instruction_count = 13;
