/* src/safety/asm_register_lookup.c — register-table lookup function.
 *
 * D-Alpha-7.5 Session F2. Implements zer_asm_register_valid (declared in
 * asm_register_tables.h) via linear scan over the vendored per-arch
 * tables generated by scripts/gen_register_tables.sh.
 *
 * F2: x86_64 only. F5/F6 add aarch64/riscv64 dispatch.
 *
 * VST-friendly C style: flat cascade, no compound conditions. Future
 * Phase 1 extraction (Session H) wraps this as the @asm_register_valid
 * predicate for verification against the linked vendored data.
 */
#include <string.h>
#include "asm_register_tables.h"

int zer_asm_register_valid(ZerArchId arch, const char *name, size_t name_len) {
    if (name == 0) {
        return 0;
    }
    if (name_len == 0) {
        return 0;
    }

    const ZerRegisterEntry *table = 0;
    if (arch == ZER_ARCH_X86_64) {
        table = zer_x86_64_registers;
    }
    /* F5/F6 will add aarch64 / riscv64 dispatch here. */

    if (table == 0) {
        return 0;
    }

    for (size_t i = 0; table[i].name != 0; i++) {
        if (table[i].name_len != name_len) {
            continue;
        }
        if (memcmp(table[i].name, name, name_len) == 0) {
            return 1;
        }
    }
    return 0;
}
