#!/bin/bash
# scripts/gen_register_tables.sh — D-Alpha-7.5 Session F2
#
# Build-time generation of per-arch register validity tables. Probes GCC
# for each candidate register name; emits valid registers to vendored
# .c files in src/safety/. Output is committed to git for reproducible
# builds and LSP-responsive runtime lookup.
#
# Usage: scripts/gen_register_tables.sh [arch]
#   arch: x86_64 (default), aarch64, riscv64
#
# Requires: gcc (or arch-cross-gcc), bash, awk.
#
# Pattern: each register name is tested by compiling a minimal C program
# that uses the register in an inline asm clobber list. If GCC accepts it,
# the register is valid for that arch. This makes GCC the authoritative
# oracle — no per-arch documentation duplication needed.

set -e
ARCH="${1:-x86_64}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CANDIDATES="$ROOT/scripts/candidates_${ARCH}.txt"
OUTPUT="$ROOT/src/safety/asm_register_tables_${ARCH}.c"

case "$ARCH" in
    x86_64)
        CC="${CC:-gcc}"
        # EXTRA_CFLAGS plumbing for future feature-enable probes.
        # Set empty by default — adding `-mavx512f -mavx512vl -mavx512bw`
        # would unlock 56 more registers (xmm/ymm/zmm 16-31 + k0-7) BUT
        # zerc's emit-time GCC invocation doesn't pass these flags, so
        # using those regs in asm would still fail to compile. Honest
        # AVX-512 support requires per-function CPU feature attributes
        # (a separate ~6-8 hr feature). Until then, simpler is correct:
        # validate only what the default GCC backend accepts.
        # Override with: EXTRA_CFLAGS="-mavx512f" make gen-asm-tables
        # if the user has manually arranged for AVX-512 emit support.
        EXTRA_CFLAGS="${EXTRA_CFLAGS:-}"
        ;;
    aarch64)
        CC="${CC:-aarch64-linux-gnu-gcc}"
        # SVE / SME require -march=armv8-a+sve / +sve2 etc.; defer until
        # ARM64 candidates list ships in F5.
        EXTRA_CFLAGS="${EXTRA_CFLAGS:-}"
        ;;
    riscv64)
        CC="${CC:-riscv64-linux-gnu-gcc}"
        # Vector extension via -march=rv64gcv; defer until F6.
        EXTRA_CFLAGS="${EXTRA_CFLAGS:-}"
        ;;
    *)
        echo "Unknown arch: $ARCH" >&2; exit 1 ;;
esac

if ! command -v "$CC" >/dev/null 2>&1; then
    echo "Cross-compiler '$CC' not found in PATH" >&2
    echo "For non-host arch, set CC=<arch>-gcc explicitly" >&2
    exit 1
fi

if [ ! -f "$CANDIDATES" ]; then
    echo "Candidate file not found: $CANDIDATES" >&2
    echo "Create scripts/candidates_${ARCH}.txt with one register per line" >&2
    exit 1
fi

# Probe a single register: compile a tiny C program with the register in
# the clobber list. Returns 0 if GCC accepts (valid), 1 otherwise.
# Uses EXTRA_CFLAGS (set per-arch above) so AVX-512 / SVE / RVV regs
# are recognized when those features are enabled at probe time.
probe_register() {
    local reg="$1"
    local rc
    echo "void f(void) { __asm__ __volatile__(\"\" ::: \"$reg\"); }" \
        | "$CC" $EXTRA_CFLAGS -x c - -c -o /dev/null 2>/dev/null
    rc=$?
    return $rc
}

# Read candidate list, probe each, accumulate valid ones.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

VALID_COUNT=0
INVALID_COUNT=0

while IFS= read -r line; do
    # Strip comments and blank lines
    reg="$(echo "$line" | awk -F'#' '{print $1}' | tr -d '[:space:]')"
    if [ -z "$reg" ]; then continue; fi

    if probe_register "$reg"; then
        echo "    {\"$reg\", $(echo -n "$reg" | wc -c)}," >> "$TMP"
        VALID_COUNT=$((VALID_COUNT + 1))
    else
        INVALID_COUNT=$((INVALID_COUNT + 1))
        echo "  skipped (GCC rejected): $reg" >&2
    fi
done < "$CANDIDATES"

# Emit the vendored .c file.
{
    echo "/* AUTO-GENERATED by scripts/gen_register_tables.sh — DO NOT EDIT BY HAND."
    echo " * Regenerate via: make gen-asm-tables"
    echo " *"
    echo " * Source: GCC probe of register clobber acceptance for arch=$ARCH."
    echo " * Compiler: $CC"
    echo " * Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo " *"
    echo " * Vendored for reproducible builds + LSP-responsive runtime lookup."
    echo " * D-Alpha-7.5 Session F2 (build-time-gen pipeline)."
    echo " */"
    echo "#include \"asm_register_tables.h\""
    echo ""
    echo "const ZerRegisterEntry zer_${ARCH}_registers[] = {"
    cat "$TMP"
    echo "    {0, 0}  /* sentinel */"
    echo "};"
    echo ""
    echo "const size_t zer_${ARCH}_register_count = ${VALID_COUNT};"
} > "$OUTPUT"

echo "Generated: $OUTPUT"
echo "  valid: $VALID_COUNT, skipped: $INVALID_COUNT"
