#!/bin/bash
# Safety Coverage Audit — extract every safety check in the compiler
# and emit a raw list. Used to build docs/safety_coverage.md (curated
# coverage matrix linking each check to abstract model + operational
# proof subset).
#
# Usage: bash tools/safety_coverage.sh [> docs/safety_coverage_raw.md]
#
# Output: markdown table with rows for:
#   - Every `checker_error` call in checker.c (compile-time rule)
#   - Every `zc_error` / `zc_warning` call in zercheck.c
#   - Every `ir_zc_error` / `ir_zc_warning` in zercheck_ir.c
#   - Every runtime trap / bounds-check emitted in generated C
#
# Many calls span multiple source lines. We preprocess by joining
# continuation lines (no trailing semicolon) before matching.
#
# The curated coverage matrix (docs/safety_coverage.md) is maintained
# by hand. This script is the source of truth for what exists; the
# curation adds model assignment, Iris technique, proof status.

set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
CHECKER="$REPO/checker.c"
ZCHECK="$REPO/zercheck.c"
ZCHECK_IR="$REPO/zercheck_ir.c"
EMITTER="$REPO/emitter.c"
PARSER="$REPO/parser.c"
LEXER="$REPO/lexer.c"

for f in "$CHECKER" "$ZCHECK" "$ZCHECK_IR" "$EMITTER" "$PARSER" "$LEXER"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found" >&2
        exit 1
    fi
done

# ---- Line-joiner: collapse continuation lines into a single logical
#      line, preserving the starting line number. Output format:
#      LINENO:joined_text
# Joins when a line doesn't end with ';' or '{' or '}' or ')' at EOL.
join_lines() {
    awk '
        BEGIN { buf = ""; startline = 0 }
        {
            if (buf == "") startline = NR
            buf = buf " " $0
            # If line ends the call (terminator char), emit.
            if ($0 ~ /;[[:space:]]*$/ || $0 ~ /\{[[:space:]]*$/ || $0 ~ /^[[:space:]]*\}/) {
                gsub(/^[[:space:]]+/, "", buf)
                print startline ":" buf
                buf = ""
            }
        }
        END {
            if (buf != "") {
                gsub(/^[[:space:]]+/, "", buf)
                print startline ":" buf
            }
        }
    ' "$1"
}

# ---- Extract error-message table from a joined-lines stream.
# Args: $1 = joined file, $2 = call-pattern (wrapped in `(...)`),
#       $3 = section header.
#
# The pattern $2 MUST be a parenthesized alternation. Because sed's
# replacement then sees 3 capture groups: \1 = line, \2 = func name
# (from $pattern), \3 = the quoted message we want. Uses `#` as sed
# delimiter to avoid conflict with `|` in patterns/messages.
extract_table() {
    local source_file="$1"
    local pattern="$2"
    local header="$3"

    echo "$header"
    echo ""
    echo "| Line | Message |"
    echo "|---|---|"

    join_lines "$source_file" \
        | grep -E "$pattern" \
        | sed -E "s#^([0-9]+):.*${pattern}\\([^\"]*\"([^\"]+)\".*#\\1@@@\\3#" \
        | grep '@@@' \
        | grep -vE '^[0-9]+@@@(static void|static inline|void |static )' \
        | sort -t'@' -k2 \
        | awk -F'@@@' '{
            msg = $2
            gsub(/\|/, "\\|", msg)
            gsub(/%\.?\*?[a-z]+/, "X", msg)
            gsub(/%ll?[du]/, "N", msg)
            gsub(/%[a-z]/, "_", msg)
            print "| " $1 " | `" msg "` |"
          }'
    echo ""
}

# ---- Header ----

cat <<'EOF'
# Safety Coverage — Raw Extraction

**Auto-generated by `tools/safety_coverage.sh`. Do not edit by hand.**

This file lists every safety check the compiler actually performs:
- Compile-time `checker_error` sites in `checker.c`.
- `zc_error` / `zc_warning` sites in `zercheck.c`.
- `ir_zc_error` / `ir_zc_warning` sites in `zercheck_ir.c` (CFG-based).
- Runtime traps (`_zer_trap`) and bounds checks (`_zer_bounds_check`)
  emitted into generated C by `emitter.c`.

Multi-line calls (where the format string is on a separate line from
the function name) are handled by folding continuation lines before
regex matching.

The **curated** coverage matrix lives in `docs/safety_coverage.md`
and maps each check to its abstract model (M1-M4), the operational
proof subset that proves it (λZER-*), the Iris technique needed,
and proof status. Every row in this raw file must appear in the
curated doc; CI enforces that.

Regenerate: `bash tools/safety_coverage.sh > docs/safety_coverage_raw.md`

---

EOF

# ---- Summary counts (folded lines) ----

CE_COUNT=$(join_lines "$CHECKER" | grep -cE '\b(checker_error|checker_warning|checker_add_diag)\(' || true)
ZC_COUNT=$(join_lines "$ZCHECK" | grep -cE '\b(zc_error|zc_warning|zc_report_invalid_use)\(' || true)
ZC_IR_COUNT=$(join_lines "$ZCHECK_IR" | grep -cE '\b(ir_zc_error|ir_zc_warning)\(' || true)
TRAP_COUNT=$(grep -cE '_zer_trap\(|_zer_bounds_check\(' "$EMITTER" || true)
PARSER_COUNT=$(join_lines "$PARSER" | grep -cE '\b(error|error_at|error_current|warn)\(' || true)
LEXER_COUNT=$(join_lines "$LEXER" | grep -cE '\berror_token\(' || true)

echo "## Summary"
echo ""
echo "| Source | Call sites (joined) |"
echo "|---|---|"
echo "| checker.c (checker_error/warning/add_diag) | $CE_COUNT |"
echo "| zercheck.c (handle-tracking zc_error/warning) | $ZC_COUNT |"
echo "| zercheck_ir.c (CFG-based ir_zc_error/warning) | $ZC_IR_COUNT |"
echo "| emitter.c (runtime _zer_trap / _zer_bounds_check) | $TRAP_COUNT |"
echo "| parser.c (syntactic error/warn) | $PARSER_COUNT |"
echo "| lexer.c (error_token) | $LEXER_COUNT |"
echo ""

# ---- Parts 1-3: compile-time error sites ----

extract_table "$CHECKER" '(checker_error|checker_warning|checker_add_diag)' "## Part 1 — Compile-time checks (checker.c)"

extract_table "$ZCHECK" '(zc_error|zc_warning)' "## Part 2 — Handle-tracking checks (zercheck.c)"

extract_table "$ZCHECK_IR" '(ir_zc_error|ir_zc_warning)' "## Part 3 — CFG-based handle checks (zercheck_ir.c)"

extract_table "$PARSER" '(error|error_at|error_current|warn)' "## Part 3b — Parser syntactic/semantic errors (parser.c)"

extract_table "$LEXER" '(error_token)' "## Part 3c — Lexer errors (lexer.c)"

# ---- Part 4: runtime trap emissions (single-line in emitter) ----

echo "## Part 4 — Runtime trap emissions (emitter.c)"
echo ""
echo "Each row is a site where the emitter inserts a runtime safety"
echo "wrapper (trap or bounds check) into the generated C code."
echo ""
echo "| Line | Trap reason |"
echo "|---|---|"

# Traps with explicit message. In emitter.c, traps are emitted via
# `emit(e, "_zer_trap(\"reason\", ...")`, so the quotes around the
# reason are backslash-escaped inside a C string literal.
# Match: _zer_trap(\"REASON\"
grep -nE '_zer_trap\(\\"[^"\\]+\\"' "$EMITTER" \
    | sed -E "s#^([0-9]+):.*_zer_trap\\(\\\\\"([^\"\\\\]+)\\\\\".*#\\1@@@\\2#" \
    | sort -t'@' -k2 -u \
    | awk -F'@@@' '{
        code = $2
        gsub(/\|/, "\\|", code)
        print "| " $1 " | `" code "` |"
      }'

# Bounds-check emissions (no arg string)
grep -nE '_zer_bounds_check\(' "$EMITTER" \
    | awk -F: '{ print "| " $1 " | `_zer_bounds_check(...)` |" }' \
    | sort -u

echo ""

# ---- Part 5: deduped predicate list ----

echo "## Part 5 — Unique safety predicates (after normalization)"
echo ""
echo "Distinct safety checks once format-string variation is stripped."
echo "This is the **coverage denominator**: every unique predicate"
echo "must appear in \`docs/safety_coverage.md\`."
echo ""

{
    join_lines "$CHECKER" | grep -E '\b(checker_error|checker_warning|checker_add_diag)\(' \
        | sed -E "s#.*\\b(checker_error|checker_warning|checker_add_diag)\\([^\"]*\"([^\"]+)\".*#\\2#"
    join_lines "$ZCHECK" | grep -E '\b(zc_error|zc_warning)\(' \
        | sed -E "s#.*\\b(zc_error|zc_warning)\\([^\"]*\"([^\"]+)\".*#\\2#"
    join_lines "$ZCHECK_IR" | grep -E '\b(ir_zc_error|ir_zc_warning)\(' \
        | sed -E "s#.*\\b(ir_zc_error|ir_zc_warning)\\([^\"]*\"([^\"]+)\".*#\\2#"
    grep -hoE '_zer_trap\("[^"]+"' "$EMITTER" \
        | sed -E 's#_zer_trap\("##' | sed 's#"$##'
    grep -c '_zer_bounds_check(' "$EMITTER" > /dev/null && echo "bounds check (_zer_bounds_check)"
    join_lines "$PARSER" | grep -E '\b(error|error_at|error_current|warn)\(' \
        | sed -E "s#.*\\b(error|error_at|error_current|warn)\\([^\"]*\"([^\"]+)\".*#\\2#"
    join_lines "$LEXER" | grep -E '\berror_token\(' \
        | sed -E "s#.*\\berror_token\\([^\"]*\"([^\"]+)\".*#\\1#"
} | grep -v '^$' \
  | grep -vE '^[[:space:]]*(static |\*|#|/\*|\*/| )' \
  | grep -vE '(checker_error|checker_warning|checker_add_diag|zc_error|ir_zc_error|zc_warning|ir_zc_warning|error_token|error_at|error_current)\(' \
  | sed -E 's#%\.?\*?[a-z]+#X#g' \
  | sed -E 's#%ll?[du]#N#g' \
  | sed -E 's#%[a-z]#_#g' \
  | sed -E 's#0x[0-9a-fA-F]+#0xN#g' \
  | sort -u > /tmp/zer_predicates.txt

UNIQUE=$(wc -l < /tmp/zer_predicates.txt)
echo "**Unique predicates: $UNIQUE**"
echo ""
echo "<details><summary>Full list (click to expand)</summary>"
echo ""
echo '```'
cat /tmp/zer_predicates.txt
echo '```'
echo ""
echo "</details>"

rm -f /tmp/zer_predicates.txt
